apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.ingressClass }}"
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress.serviceName }}
          servicePort: {{ .Values.ingress.servicePort }}
        path: {{ .Values.ingress.path }}
